### ISSUE TITLE
Can all output be shown? Seems to be cutoff by a limit.

### ISSUE THREAD

**Issue by guzman109** [sdsc-hpc-training-org/hello_icicle_auth_clients#16]
I understand for 'all' command, but 'oneByName' and 'allPropertiesForNode' should have an output you can scroll through and see everything. Perhaps in a pretty print format.

Example of my output:
![image](https://github.com/sdsc-hpc-training-org/hello_icicle_auth_clients/assets/42706936/c7483dcc-423f-47c4-95bf-1b1a4e581e62)

**Comment by AD1616** [comment]
Yes, implemented a package called Datascroller to display any kind of Node data. For other data, a simple print seems to do the trick.
